import time
import main

apple = Company('apple')
print('Ticker: ', apple.ticker)
print('Keyword: ', apple.keyword)
print('The latest Closing price: ', round(apple.price()['Close'].values[0],2))
print('Summary: ', apple.summary())
print('Prediction: ', apple.prediction())
print('Sending email...')
apple.email()
print('Sending email successfully.')

print('start monitor apple')
apple.monitor()
print(apple)
time.sleep(1)
print(sleep)
time.sleep(1)
time.sleep(1)
print(sleep)
time.sleep(1)
time.sleep(1)
print(sleep)
time.sleep(1)
time.sleep(1)
print(sleep)
time.sleep(1)
iime.sleep(1)
print(sleep)
time.sleep(1)
apple.monitor()
